name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: cd /home/runner/work/engenharia-da-pizza/engenharia-da-pizza
      run: npm install
    - name: Unit Tests
      run: npm test
