name: Node.js CI

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - run: cd ../engenharia-da-pizza
    - name: Install dependencies
      run: npm install
    - name: Unit Tests
      run: npm test